import type { Metadata } from "next";
import { Montserrat ,Inter } from "next/font/google";
import "./globals.css";
import MobileNav from "@/components/MobileNav";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NDA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MobileNav>
          {children}
        </MobileNav>
      </body>
    </html>
  );
}
